# Morning Market Report

Professional morning market report generator using Bloomberg API and free financial data sources.

## 🚀 Features

- **Bloomberg Terminal Integration** - Real-time institutional data when available
- **Free API Fallbacks** - Alpha Vantage, Twelve Data, News API, Exchange Rate API
- **AI-Powered Analysis** - Professional reports generated by Claude AI
- **Email Delivery** - Automated morning reports sent to your team
- **Hybrid Data Quality** - Institutional grade when Bloomberg available, reliable coverage always

## 📊 Data Sources

### Primary (Bloomberg Terminal)
- Real-time futures and equity data
- Professional market depth
- Institutional-grade accuracy

### Fallback (Free APIs)
- **Alpha Vantage** - Stock quotes and market data
- **Twelve Data** - Real-time and historical prices
- **News API** - Market news and developments
- **Exchange Rate API** - Currency rates
- **Finnhub** - Additional market data

## ⚡ Quick Start

### 1. Clone and Install
```bash
git clone https://github.com/yourusername/morning-market-report.git
cd morning-market-report
npm install
```

### 2. Setup Environment Variables
```bash
cp env-market.example .env-market
# Edit .env-market with your API keys
```

### 3. Run Market Report
```bash
# Make sure Bloomberg Terminal is running (if you want Bloomberg data)
npm run report
```

## 🔑 Required API Keys

### Essential
- **Anthropic API** - For AI report generation ([Get key](https://console.anthropic.com))
- **Gmail App Password** - For email delivery ([Setup guide](https://support.google.com/accounts/answer/185833))

### Recommended (Free)
- **Alpha Vantage** - [Free tier: 25 calls/day](https://alphavantage.co/support/#api-key)
- **Twelve Data** - [Free tier: 800 calls/day](https://twelvedata.com)
- **News API** - [Free tier: 100 calls/day](https://newsapi.org)
- **Exchange Rate API** - [Free tier: 1500 calls/month](https://exchangerate-api.com)

## 📧 Email Setup

1. **Enable 2-Factor Authentication** on your Gmail account
2. **Generate App Password:**
   - Go to Google Account → Security → 2-Step Verification → App passwords
   - Generate password for "Mail"
   - Use this 16-character password (not your regular Gmail password)

## 🏛️ Bloomberg Setup

### Desktop API (Most Common)
- Requires Bloomberg Terminal running and logged in
- Uses localhost connection (127.0.0.1:8194)
- No additional Bloomberg credentials needed

### Server API
- Contact your Bloomberg administrator for:
  - Server hostname/IP
  - Application name and key
  - Port number (usually 8194)

## 🎯 Usage

### Run Locally
```bash
npm start                 # Generate and send report
npm run test             # Test dependencies
npm run setup            # Install dependencies
```

### GitHub Actions (Free APIs Only)
The script automatically detects GitHub Actions environment and uses only free APIs since Bloomberg Terminal isn't available remotely.

## 📊 Data Quality Levels

- **🏛️ INSTITUTIONAL** - 75%+ Bloomberg data (best accuracy)
- **🔄 HYBRID** - 25-75% Bloomberg data (good balance)  
- **📊 FREE** - 0-25% Bloomberg data (reliable coverage)

## 📁 Output

Reports are saved to `/market-reports/` directory:
- `morning-report-YYYY-MM-DD.md` - Daily reports
- Raw data JSON files for analysis
- Email delivery to configured recipients

## 🛠️ Troubleshooting

### Bloomberg Connection Issues
- Ensure Bloomberg Terminal is running and logged in
- Check if bbcomm.exe process is active (Windows)
- Verify you're on the same machine as Terminal

### API Rate Limits
- Free APIs have daily/monthly limits
- Script automatically handles rate limiting
- Consider upgrading to paid tiers for higher limits

### Email Issues
- Use Gmail App Password, not regular password
- Enable 2-factor authentication first
- Check Gmail security settings

## 🔒 Security

- Never commit `.env-market` file to Git
- Use environment variables for all secrets
- Bloomberg Desktop API doesn't require API keys (uses Terminal session)
- Free API keys are safe to use but keep them private

## 📈 Upgrade Path

### From Free to Professional
1. **Bloomberg Terminal** - $2,000+/month (institutional data)
2. **Paid API Tiers** - Higher limits and more features
3. **Bloomberg Server API** - Remote access capabilities

## 🤝 Contributing

1. Fork the repository
2. Create feature branch (`git checkout -b feature/amazing-feature`)
3. Commit changes (`git commit -m 'Add amazing feature'`)
4. Push to branch (`git push origin feature/amazing-feature`)
5. Open Pull Request

## 📄 License

This project is licensed under the MIT License - see the LICENSE file for details.

## ⚠️ Disclaimer

This software is for informational purposes only. Not financial advice. Use at your own risk. Bloomberg Terminal and API access subject to Bloomberg's terms and conditions.

---

**Made with ♥️ for professional traders and analysts**
