name: Verified Daily Market Report

on:
  schedule:
    # Runs at 12:00 PM UTC daily
    - cron: '0 12 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-verified-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        echo "📦 Installing required dependencies..."
        npm install axios
        npm install nodemailer
        echo "✅ Core dependencies installed"
        
    - name: Verify environment
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        WORK_EMAIL_LIST: ${{ secrets.WORK_EMAIL_LIST }}
      run: |
        echo "🔍 Verifying environment variables..."
        echo "ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY && '✅ Present' || '❌ Missing' }}"
        echo "ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY && '✅ Present' || '⚠️ Optional - Missing' }}"
        echo "FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY && '✅ Present' || '⚠️ Optional - Missing' }}"
        echo "POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY && '✅ Present' || '⚠️ Optional - Missing' }}"
        echo "GMAIL_USER: ${{ secrets.GMAIL_USER && '✅ Present' || '❌ Missing' }}"
        echo "GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD && '✅ Present' || '❌ Missing' }}"
        echo "WORK_EMAIL_LIST: ${{ secrets.WORK_EMAIL_LIST && '✅ Present' || '❌ Missing' }}"
        
    - name: Generate Verified Market Report
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        WORK_EMAIL_LIST: ${{ secrets.WORK_EMAIL_LIST }}
      run: |
        echo "🚀 Starting verified market report generation..."
        node generate-verified-report.js
        echo "✅ Report generation completed"
        
    - name: Verify report generation
      run: |
        echo "🔍 Verifying generated files..."
        if [ -d "reports" ]; then
          echo "✅ Reports directory exists"
          ls -la reports/
          
          # Check if today's report was generated
          TODAY=$(date +'%Y-%m-%d')
          if [ -f "reports/verified-market-report-${TODAY}.md" ]; then
            echo "✅ Today's report generated: verified-market-report-${TODAY}.md"
            echo "📊 Report size: $(wc -c < reports/verified-market-report-${TODAY}.md) bytes"
          else
            echo "⚠️ Today's report not found"
          fi
          
          if [ -f "reports/latest-verified-report.md" ]; then
            echo "✅ Latest report link created"
          fi
          
          if [ -f "reports/verification-data-${TODAY}.json" ]; then
            echo "✅ Verification data saved"
          fi
        else
          echo "❌ Reports directory not found"
          exit 1
        fi
        
    - name: Commit and push reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        
        # Add all report files
        git add reports/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "📝 No new reports to commit"
        else
          TODAY=$(date +'%Y-%m-%d')
          git commit -m "📈 Verified daily market report - ${TODAY}

          Generated: $(date +'%Y-%m-%d %H:%M:%S UTC')
          Status: Accuracy verified and validated
          Files: Report, verification data, and latest link
          
          Automated by GitHub Actions 🤖"
          
          echo "📤 Pushing verified report to repository..."
          git push
          echo "✅ Report successfully committed and pushed"
        fi
        
    - name: Report generation summary
      if: always()
      run: |
        echo "
        📊 === MARKET REPORT GENERATION SUMMARY ===
        🕐 Time: $(date +'%Y-%m-%d %H:%M:%S UTC')
        📈 Report Type: Verified Daily Market Report
        🔍 Accuracy: Enhanced with fact-checking
        📧 Email: Automated delivery
        📁 Storage: GitHub repository
        🤖 Automation: GitHub Actions
        
        ✅ Process completed successfully!
        "

  # Optional: Send notification on failure
  notify-on-failure:
    runs-on: ubuntu-latest
    needs: generate-verified-report
    if: failure()
    
    steps:
    - name: Report failure
      run: |
        echo "❌ Market report generation failed"
        echo "⏰ Failure time: $(date +'%Y-%m-%d %H:%M:%S UTC')"
        echo "🔍 Check the logs above for detailed error information"
        echo "📧 Consider setting up email notifications for failures"
